name: build-test

# trigger on any push
# but not on master or tags
# and only for dockerfile-related modifications
on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
      - "!master"
    paths:
      - "Dockerfile"
      - "supported_versions.json"
      - "hashicorp.asc"
      - "tests/*"
      - ".dockerignore"
      - "hadolint.yaml"
      - ".github/workflows/build-test.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

env:
  IMAGE_NAME: "aws-helm-kubectl"

jobs:
  load_supported_versions:
    runs-on: ubuntu-22.04

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Save supported versions as output
        id: set-matrix
        run: |
          VERSIONS=$(cat ./supported_versions.json | jq -c)
          echo "matrix=${VERSIONS}" >> $GITHUB_OUTPUT

  build-test:
    runs-on: ubuntu-22.04
    needs: load_supported_versions
    strategy:
      matrix: ${{ fromJSON(needs.load_supported_versions.outputs.matrix) }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Print Matrix Versions
        run: |
          echo Helm Version: ${{matrix.helm}}
          echo Kubectl Version: ${{matrix.kubectl}}
          echo AWS Version: ${{matrix.aws-cli}}

      - name: Save branch name as env var
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and save image tag
        run: echo "IMAGE_TAG=${BRANCH}_aws-${{ matrix.aws-cli }}_helm-${{ matrix.helm }}_kubectl-${{ matrix.kubectl }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export container image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          build-args: |
            HELM_VERSION=${{ matrix.helm }}
            KUBECTL_VERSION=${{ matrix.kubectl }}
            AWS_CLI_VERSION=${{ matrix.aws-cli }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Build container image for ARM 64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          build-args: |
            HELM_VERSION=${{ matrix.helm }}
            KUBECTL_VERSION=${{ matrix.kubectl }}
            AWS_CLI_VERSION=${{ matrix.aws-cli }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=min
